package blog.groundhao.com.mygroundhao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import blog.groundhao.com.mygroundhao.JokeCache;
import blog.groundhao.com.mygroundhao.NothingCache;
import blog.groundhao.com.mygroundhao.PictureCache;
import blog.groundhao.com.mygroundhao.SisterCache;
import blog.groundhao.com.mygroundhao.VideoCache;

import blog.groundhao.com.mygroundhao.JokeCacheDao;
import blog.groundhao.com.mygroundhao.NothingCacheDao;
import blog.groundhao.com.mygroundhao.PictureCacheDao;
import blog.groundhao.com.mygroundhao.SisterCacheDao;
import blog.groundhao.com.mygroundhao.VideoCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jokeCacheDaoConfig;
    private final DaoConfig nothingCacheDaoConfig;
    private final DaoConfig pictureCacheDaoConfig;
    private final DaoConfig sisterCacheDaoConfig;
    private final DaoConfig videoCacheDaoConfig;

    private final JokeCacheDao jokeCacheDao;
    private final NothingCacheDao nothingCacheDao;
    private final PictureCacheDao pictureCacheDao;
    private final SisterCacheDao sisterCacheDao;
    private final VideoCacheDao videoCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jokeCacheDaoConfig = daoConfigMap.get(JokeCacheDao.class).clone();
        jokeCacheDaoConfig.initIdentityScope(type);

        nothingCacheDaoConfig = daoConfigMap.get(NothingCacheDao.class).clone();
        nothingCacheDaoConfig.initIdentityScope(type);

        pictureCacheDaoConfig = daoConfigMap.get(PictureCacheDao.class).clone();
        pictureCacheDaoConfig.initIdentityScope(type);

        sisterCacheDaoConfig = daoConfigMap.get(SisterCacheDao.class).clone();
        sisterCacheDaoConfig.initIdentityScope(type);

        videoCacheDaoConfig = daoConfigMap.get(VideoCacheDao.class).clone();
        videoCacheDaoConfig.initIdentityScope(type);

        jokeCacheDao = new JokeCacheDao(jokeCacheDaoConfig, this);
        nothingCacheDao = new NothingCacheDao(nothingCacheDaoConfig, this);
        pictureCacheDao = new PictureCacheDao(pictureCacheDaoConfig, this);
        sisterCacheDao = new SisterCacheDao(sisterCacheDaoConfig, this);
        videoCacheDao = new VideoCacheDao(videoCacheDaoConfig, this);

        registerDao(JokeCache.class, jokeCacheDao);
        registerDao(NothingCache.class, nothingCacheDao);
        registerDao(PictureCache.class, pictureCacheDao);
        registerDao(SisterCache.class, sisterCacheDao);
        registerDao(VideoCache.class, videoCacheDao);
    }
    
    public void clear() {
        jokeCacheDaoConfig.getIdentityScope().clear();
        nothingCacheDaoConfig.getIdentityScope().clear();
        pictureCacheDaoConfig.getIdentityScope().clear();
        sisterCacheDaoConfig.getIdentityScope().clear();
        videoCacheDaoConfig.getIdentityScope().clear();
    }

    public JokeCacheDao getJokeCacheDao() {
        return jokeCacheDao;
    }

    public NothingCacheDao getNothingCacheDao() {
        return nothingCacheDao;
    }

    public PictureCacheDao getPictureCacheDao() {
        return pictureCacheDao;
    }

    public SisterCacheDao getSisterCacheDao() {
        return sisterCacheDao;
    }

    public VideoCacheDao getVideoCacheDao() {
        return videoCacheDao;
    }

}
